// <auto-generated />
using ASPNET360SIte.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPNET360SIte.Migrations.ASPNET360SIte
{
    [DbContext(typeof(ASPNET360SIteContext))]
    partial class ASPNET360SIteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPNET360SIte.Models.FloorPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomPropertyID");

                    b.Property<string>("FloorPlanLabel");

                    b.Property<string>("MainImagePath");

                    b.HasKey("ID");

                    b.ToTable("FloorPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
